"""Run migration

Revision ID: 43b526aa1da7
Revises:
Create Date: 2024-09-23 21:48:13.950192

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "43b526aa1da7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cities_id"), "cities", ["id"], unique=False)
    op.create_index(op.f("ix_cities_name"), "cities", ["name"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "favorite_cities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("city_id", sa.BigInteger(), nullable=False),
        sa.Column("allow_notifications", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["cities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "city_id", name="unique_user_city"),
    )
    op.create_index(
        op.f("ix_favorite_cities_city_id"),
        "favorite_cities",
        ["city_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_favorite_cities_id"),
        "favorite_cities",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_favorite_cities_user_id"),
        "favorite_cities",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "weather",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("city_id", sa.BigInteger(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_weather_city_id"), "weather", ["city_id"], unique=False)
    op.create_index(op.f("ix_weather_id"), "weather", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weather_id"), table_name="weather")
    op.drop_index(op.f("ix_weather_city_id"), table_name="weather")
    op.drop_table("weather")
    op.drop_index(op.f("ix_favorite_cities_user_id"), table_name="favorite_cities")
    op.drop_index(op.f("ix_favorite_cities_id"), table_name="favorite_cities")
    op.drop_index(op.f("ix_favorite_cities_city_id"), table_name="favorite_cities")
    op.drop_table("favorite_cities")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_cities_name"), table_name="cities")
    op.drop_index(op.f("ix_cities_id"), table_name="cities")
    op.drop_table("cities")
    # ### end Alembic commands ###
