"""add unique constraint on table favorite_cities

Revision ID: f8aa0866721b
Revises: 9bb669f002a0
Create Date: 2024-09-22 21:32:56.386580

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "f8aa0866721b"
down_revision = "9bb669f002a0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_user_city",
        "favorite_cities",
        ["user_id", "city_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_user_city", "favorite_cities", type_="unique")
    # ### end Alembic commands ###
