"""dummy_model: added columns created_at, updated_at

Revision ID: 832273a50d28
Revises:
Create Date: 2024-09-22 12:49:21.647349

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "832273a50d28"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dummy_model",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "dummy_model",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dummy_model", "updated_at")
    op.drop_column("dummy_model", "created_at")
    # ### end Alembic commands ###
