"""add relationships on city and user model

Revision ID: a17c8c453503
Revises: 2d1d0add32dc
Create Date: 2024-09-22 20:21:41.031401

"""

# revision identifiers, used by Alembic.
revision = "a17c8c453503"
down_revision = "2d1d0add32dc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
