"""add foreign keys on table favorite_cities

Revision ID: 2d1d0add32dc
Revises: 5ddd8bb61a19
Create Date: 2024-09-22 20:18:27.451540

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "2d1d0add32dc"
down_revision = "5ddd8bb61a19"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None,
        "favorite_cities",
        "cities",
        ["city_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "favorite_cities",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "favorite_cities", type_="foreignkey")  # type: ignore
    op.drop_constraint(None, "favorite_cities", type_="foreignkey")  # type: ignore
    # ### end Alembic commands ###
