"""update

Revision ID: 9bb669f002a0
Revises: a17c8c453503
Create Date: 2024-09-22 20:39:03.849168

"""

# revision identifiers, used by Alembic.
revision = "9bb669f002a0"
down_revision = "a17c8c453503"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
