"""added city model, favorite cities model and relationships

Revision ID: b0ad02727708
Revises: 832273a50d28
Create Date: 2024-09-22 16:41:29.274795

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b0ad02727708"
down_revision = "832273a50d28"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("sunrise", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sunset", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cities_id"), "cities", ["id"], unique=False)
    op.create_index(op.f("ix_cities_name"), "cities", ["name"], unique=False)
    op.create_table(
        "favorite_cities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("city_id", sa.BigInteger(), nullable=False),
        sa.Column("allow_notifications", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_favorite_cities_city_id"),
        "favorite_cities",
        ["city_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_favorite_cities_id"),
        "favorite_cities",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_favorite_cities_user_id"),
        "favorite_cities",
        ["user_id"],
        unique=False,
    )
    op.drop_constraint("users_email_key", "users", type_="unique")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint("users_email_key", "users", ["email"])
    op.drop_index(op.f("ix_favorite_cities_user_id"), table_name="favorite_cities")
    op.drop_index(op.f("ix_favorite_cities_id"), table_name="favorite_cities")
    op.drop_index(op.f("ix_favorite_cities_city_id"), table_name="favorite_cities")
    op.drop_table("favorite_cities")
    op.drop_index(op.f("ix_cities_name"), table_name="cities")
    op.drop_index(op.f("ix_cities_id"), table_name="cities")
    op.drop_table("cities")
    # ### end Alembic commands ###
